---
# task file for wildfly

- name: Create wildfly etc directory
  file:
    path: '{{ wildfly_conf_dir }}'
    state: directory
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0750'

- name: Copy wildfly configuration
  template:
    src: wildfly.conf.j2
    dest: '{{ wildfly_conf_dir }}/wildfly.conf'
    owner: root
    group: root
    mode: '0640'
  notify:
    - restart wildfly
    - change standalone data mode

- name: Copy wildfly properties file
  template:
    src: wildfly.properties.j2
    dest: '{{ wildfly_conf_dir }}/wildfly.properties'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0640'
  notify:
    - restart wildfly
    - change standalone data mode

- name: Copy wildfly init script
  template: src=wildfly.init.j2 dest={{ wildfly_init_dir }}/wildfly owner=root
            group=root mode=0750
  when: ansible_service_mgr == 'init'
  notify:
    - restart wildfly
    - change standalone data mode

- name: Check whether Firewalld Service is active
  service: name=firewalld
  register: firewalld_result

- include: firewalld.yml
  when: firewalld_result.status.ActiveState == 'active'

- name: Copy wildfly systemd unit file
  template: src=wildfly.service.j2 dest={{ wildfly_systemd_dir }}/wildfly.service owner=root
            group=root mode=0640
  when: ansible_service_mgr == 'systemd'
  notify:
    - restart wildfly
    - change standalone data mode

- name: Enable and start the service
  service:
    name: wildfly
    state: started
    enabled: yes

- name: Change standalone data mode
  file:
    path: '{{ wildfly_dir }}/standalone/data'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0750'
    recurse: yes
    state: directory

- name: Delete wildfly tar file
  file:
    path: '{{ wildfly_download_dir }}/{{ wildfly_download_file }}'
    state: absent

- name: Create a version file
  template:
    src: version.j2
    dest: '{{ wildfly_version_file }}'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: '0750'
